@startuml TerraArgila
!include .\\.\Controllers\AdminController.puml
!include .\\.\Controllers\AdminInviteController.puml
!include .\\.\Controllers\CategoriesController.puml
!include .\\.\Controllers\DashboardController.puml
!include .\\.\Controllers\HomeController.puml
!include .\\.\Controllers\MaterialsController.puml
!include .\\.\Controllers\OrdersController.puml
!include .\\.\Controllers\PaymentsController.puml
!include .\\.\Controllers\ProductsController.puml
!include .\\.\Controllers\SupplierDashboardController.puml
!include .\\.\Controllers\TagsController.puml
!include .\\.\Controllers\UserActivityController.puml
!include .\\.\Controllers\VendorDashboardController.puml
!include .\\.\Models\AdminDashboardViewModel.puml
!include .\\.\Models\Category.puml
!include .\\.\Models\ErrorViewModel.puml
!include .\\.\Models\Invitation.puml
!include .\\.\Models\Item.puml
!include .\\.\Models\ItemImage.puml
!include .\\.\Models\LogEntry.puml
!include .\\.\Models\Material.puml
!include .\\.\Models\Order.puml
!include .\\.\Models\OrderItem.puml
!include .\\.\Models\Payment.puml
!include .\\.\Models\Product.puml
!include .\\.\Models\ProductMaterial.puml
!include .\\.\Models\StockMovement.puml
!include .\\.\Models\SupplierDashboardViewModel.puml
!include .\\.\Models\Tag.puml
!include .\\.\Models\User.puml
!include .\\.\Models\UserActivity.puml
!include .\\.\Models\UserMaterialFavorite.puml
!include .\\.\Models\UserViewModel.puml
!include .\\.\Models\VendorDashboardViewModel.puml
!include .\\.\Views\Admin\Dashboard.cshtml.puml
!include .\\.\Views\Orders\Index.cshtml.puml
!include .\\.\Views\Orders\OrdersList.cshtml.puml
!include .\\.\Views\SupplierDashboard\Index.cshtml.puml
!include .\\.\Views\VendorDashboard\Index.cshtml.puml
@enduml
