# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, test, and deploy ASP.Net Core app to Azure Web App - terraeargila7

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

  build:
    runs-on: windows-latest
    needs: test
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/master' # Garante que o deploy só roda na master
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'terraeargila7'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2165AAC4657D47E3920EEEE605C5148C }}
          
      - name: Instalar a ferramenta dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 7.*

      - name: Listar arquivos recursivamente
        run: Get-ChildItem -Recurse

      - name: Update database
        run: dotnet ef database update --project "ESA-Terra-Argila.csproj" --startup-project "ESA-Terra-Argila.csproj"
        env:
          DOTNET_ROOT: ${{env.DOTNET_ROOT}}
          ASPNETCORE_ENVIRONMENT: 'Production'
          ConnectionStrings__DefaultConnection: ${{ secrets.CONNECTION_STRING }}
